"""
Hand-written ground truth for the target-identity audit population.

WHAT THESE ARE FOR
------------------
An operating point chosen on a population and then validated on that same
population reports its own selection back as an achieved error rate. So the
thresholds in `target_identity.OperatingPoint` are chosen against a synthetic
population generated by `entity_resolution.synthetic` -- which shares no code
with the resolver and plants its own truth -- and audited here, on real families
the selection never saw.

The split is by FAMILY and not by pair, so that a family cannot contribute a pair
to threshold selection and another pair to the confirmation of that selection.
All five real families below are reserved for the audit side; nothing here is
ever used for calibration.

WHY EACH RECORD IS LABELLED THE WAY IT IS
-----------------------------------------
``family`` is the leave-one-family-out unit. ``target`` is the claim being
scored: two records share a ``target`` exactly when a correct resolver MUST place
them in one biological family, and share only a ``family`` when they are related
and must stay apart. The four SARS-CoV-2 spike constructs are one family and
four different targets, which is what makes them a test rather than a formality.

The digests are the first 32 hex characters of the SHA-256 of the cleaned antigen
sequence, and every one of them is reproduced from the sequences committed in
`tests/fixtures_target_identity.py` by
`test_target_identity_engine.py::test_curated_labels_match_the_committed_fixtures`.
A label whose digest drifted away from its sequence would silently score a
different record than the one it describes.
"""
from __future__ import annotations

from typing import FrozenSet, Mapping, Tuple

from .target_identity import CuratedLabel

#: The error asymmetry, declared before any measurement. A false MERGE is the
#: more expensive error: it destroys target diversity, corrupts every per-target
#: number computed downstream, and is invisible to a leakage audit because a
#: merged pair never straddles anything. A false SPLIT costs leakage, which a
#: leakage audit does detect and report. The operating point is therefore chosen
#: to tolerate more false splits than false merges. This string is carried on
#: every `ErrorReport` so it cannot be chosen after the numbers are known, and it
#: is byte-identical to the one predeclared in the acceptance fixtures.
PREDECLARED_ERROR_ASYMMETRY = "tolerate_false_splits_over_false_merges"

#: Families reserved for the audit population. Threshold selection may not touch
#: them; `entity_resolution.synthetic` supplies the calibration side.
PINNED_AUDIT_FAMILIES: Tuple[str, ...] = (
    "sars_cov2_spike",
    "her2_igkc_fusion",
    "il12_il23",
    "influenza_b_haemagglutinin",
    "rac1",
)

CURATED_LABELS: Mapping[str, CuratedLabel] = {
    # --- sars_cov2_spike: one family, four targets ------------------------- #
    "3a917f8d4893e8791048ede5f795f0b1": CuratedLabel(
        family="sars_cov2_spike", target="spike_ntd",
        note="287-aa Omicron spike N-terminal domain",
    ),
    "af4a498a5a5050210a542511ee691e81": CuratedLabel(
        family="sars_cov2_spike", target="spike_ntd",
        note="289-aa Omicron spike NTD: the 287-mer plus an interior HV insertion",
    ),
    "be45fbf1376c9e681f595e2a2da4a21f": CuratedLabel(
        family="sars_cov2_spike", target="spike_ntd",
        note="292-aa wild-type spike NTD; same domain, different variant",
    ),
    "af5ee94d7b888059635fa1e91fc810f8": CuratedLabel(
        family="sars_cov2_spike", target="spike_rbd",
        note="223-aa receptor-binding domain; shares no 8-mer with the NTD",
    ),
    "5fff89447258877507d3143480e1c481": CuratedLabel(
        family="sars_cov2_spike", target="spike_s1",
        note="539-aa S1 fragment; contains near-copies of both the NTD and the RBD",
    ),
    "de0d346e851eb0bd502970f1f24ee52f": CuratedLabel(
        family="sars_cov2_spike", target="spike_s2",
        note="666-aa S2 region; shares no 8-mer with any of the other three",
    ),
    # --- her2_igkc_fusion: a container and the two things inside it --------- #
    "c6627db2e640c16d92cb55e9745cff6a": CuratedLabel(
        family="her2_igkc_fusion", target="fab_her2_fusion",
        note="1057-aa composite: Fab light + GGGGGGGG + Fab heavy + GGGGGGGG + HER2 ECD",
    ),
    "ae38d43ea82403ec59e716cdfe9c5d3d": CuratedLabel(
        family="her2_igkc_fusion", target="her2_ectodomain",
        note="607-aa HER2 extracellular domain",
    ),
    "4ee35229afcd289ca9edacc9151bde61": CuratedLabel(
        family="her2_igkc_fusion", target="her2_ectodomain",
        note="564-aa HER2 ECD truncation; same target, different construct",
    ),
    "d591c34db571eedb43a8703ef3c4eec2": CuratedLabel(
        family="her2_igkc_fusion", target="igkc_constant_domain",
        note="107-aa human IGKC constant domain, P01834; a different protein entirely",
    ),
    # --- il12_il23: two genes sharing one PDB entry ------------------------- #
    "18441f075ed6b551c796f246a6bac733": CuratedLabel(
        family="il12_il23", target="il23a", note="189-aa IL23A, Q9NPF7",
    ),
    "997621c8a338440d7db35c06ca18632d": CuratedLabel(
        family="il12_il23", target="il12b",
        note="328-aa IL12B, P29460; different gene, shares PDB 4GRW with IL23A",
    ),
    # --- influenza_b_haemagglutinin: one target, three strains -------------- #
    "0fe84f645dff0dc297d214c34b36214d": CuratedLabel(
        family="influenza_b_haemagglutinin", target="influenza_b_ha",
        note="345-aa HA, P18880",
    ),
    "3d9e7e7feb2c7a686afb02da5b52fb21": CuratedLabel(
        family="influenza_b_haemagglutinin", target="influenza_b_ha",
        note="360-aa HA, Q67378",
    ),
    "fca047d7a0b2c4bccfb3c27a43f2bed0": CuratedLabel(
        family="influenza_b_haemagglutinin", target="influenza_b_ha",
        note="362-aa HA, Q67381",
    ),
    # --- rac1: one sequence, two accessions --------------------------------- #
    "48db732bf13b377c21467adf0bac39d4": CuratedLabel(
        family="rac1", target="rac1", note="192 aa carrying both P63000 and P63001",
    ),
}

#: Pairs whose correct answer was never settled, excluded from scoring and
#: COUNTED rather than dropped. The 539-aa S1 fragment contains near-copies of
#: both the NTD and the RBD, so whether it is "the same target" as either is a
#: question about what a construct boundary means, not about what the sequences
#: are. Scoring it either way would report a judgement call as an error rate.
#: Every excluded pair is listed explicitly; there is no rule that could quietly
#: grow this set.
UNADJUDICATED_PAIRS: FrozenSet[Tuple[str, str]] = frozenset({
    ("3a917f8d4893e8791048ede5f795f0b1", "5fff89447258877507d3143480e1c481"),
    ("5fff89447258877507d3143480e1c481", "af4a498a5a5050210a542511ee691e81"),
    ("5fff89447258877507d3143480e1c481", "be45fbf1376c9e681f595e2a2da4a21f"),
    ("5fff89447258877507d3143480e1c481", "af5ee94d7b888059635fa1e91fc810f8"),
})
